### ISSUE TITLE
Google Map not working

### ISSUE THREAD

**Issue by bipin24x7** [Mindfly/uLocate#6]
Hi Heather,
I see its been more than almost 4-5 years there is any code changes to this package / plugin. Google has changed many rules and policy around Google Map API and this plugin is not working as expected. There are many code changes required. I have few code changes in mind based on my client project expectation. However, I think its best we enhance this plugin and make required code changes and release new plugin for Umbraco v7.x.

I can help with some code changes. Please let me know if we can work together on this to make it work.

Thanks,
Bipin

**Comment by hfloyd** [comment]
Hi Bipin, 

Mindfly, the company which created this project originally no longer exists. And this isn't something I was very involved with myself, and I'm not planning to continue working on it at this time. 

My suggestion is to go ahead  and fork the repository and take it over. If you want to keep it alive, I'd be happy to add a note to this project that people should work from your repository.

**Comment by bipin24x7** [comment]
Hi Heather,
Thank you for your response. It would be great if you can grant me check-in access to Master branch and I can make changes to that. Otherwise, I can go ahead and create new fork.

**Comment by hfloyd** [comment]
I've made you an admin on the project. Have fun! :-)

**Comment by bipin24x7** [comment]
Thank you. I will continue with changes. :)
